export const WORLD_SIZE = 160;

export const PLAYER = {
  radius: 0.5,
  speed: 9,
  maxHp: 100,
};

export const ENEMY_TYPES = {
  grunt: {
    radius: 0.9,
    height: 2.0,
    speed: 3.2,
    hp: 25,
    damage: 8,
    xp: 3,
    color: 0xc0392b,
    model: "/models/goblin_mini1.bbmodel",
  },
  runner: {
    radius: 0.75,
    height: 1.6,
    speed: 5.6,
    hp: 12,
    damage: 6,
    xp: 2,
    color: 0xe67e22,
    model: "/models/goblin_mini2.bbmodel",
  },
  brute: {
    radius: 1.3,
    height: 2.8,
    speed: 1.8,
    hp: 120,
    damage: 20,
    xp: 12,
    color: 0x8e44ad,
    model: "/models/goblin_mini3.bbmodel",
  },
  knight: {
    radius: 1.2,
    height: 2.6,
    speed: 2.2,
    hp: 160,
    damage: 25,
    xp: 18,
    color: 0x4a4a6a,
    model: "/models/goblin_knight.bbmodel",
  },
  leader: {
    radius: 1.0,
    height: 2.2,
    speed: 3.8,
    hp: 60,
    damage: 12,
    xp: 10,
    color: 0xd4a017,
    model: "/models/goblin_leader.bbmodel",
  },
  mage: {
    radius: 1.0,
    height: 2.4,
    speed: 3.0,
    hp: 55,
    damage: 10,
    xp: 15,
    color: 0x26c6da,
    model: "/models/goblin_mage.bbmodel",
    ranged: true,
    range: 16,
    fireInterval: 2.2,
    projectileSpeed: 12,
  },
  boss: {
    radius: 1.9,
    height: 4.4,
    speed: 1.9,
    hp: 550,
    damage: 34,
    xp: 40,
    color: 0x7b1fa2,
    model: "/models/goblin_mini3.bbmodel",
  },
};

// Elite and boss cadence / stat multipliers.
export const WAVES = {
  eliteFirst: 35,
  eliteEvery: 40,
  bossFirst: 120,
  bossEvery: 120,
  eliteHpMul: 5,
  eliteDmgMul: 1.5,
  eliteSizeMul: 1.35,
  eliteXpMul: 3,
  bossHpMul: 1,
  bossSizeMul: 1.6,
  bossXpMul: 8,
  bossVolleyEvery: 3.2,
  bossVolleyCount: 10,
  bossCrateDrops: 2,
};

export const GAME = {
  startHp: 100,
  startFireRate: 3,
  baseDamage: 12,
  projectileSpeed: 34,
  autoRange: 26,
  playerShotRange: 32,
  maxEnemies: 160,
  enemyScalePerMinute: 1.2,
  maxWeapons: 5,
  rerollsPerLevel: 1,
  xpToLevel: (level) => 10 + (level - 1) * 8 + Math.floor((level - 1) ** 1.6),
};

// Breakable crates: random world objects that drop a power-up when destroyed.
export const CRATES = {
  max: 5,
  spawnEvery: 6,
  hp: 18,
  radius: 0.7,
  bombRadius: 14,
  bombDamage: 60,
  freezeTime: 3.5,
  freezeRadius: 12,
};

// Permanent, essence-bought upgrades (persisted in localStorage by meta.js).
export const META = {
  vitality: { name: "Vitality", icon: "\u2764", desc: "+10 starting max HP", maxLevel: 5, per: 10, stat: "maxHp", cost: (l) => 60 + l * 40 },
  wrath: { name: "Wrath", icon: "\u2020", desc: "+5% all damage", maxLevel: 5, per: 0.05, stat: "damage", cost: (l) => 80 + l * 50 },
  swiftness: { name: "Swiftness", icon: "\u27a4", desc: "+3% move speed", maxLevel: 5, per: 0.03, stat: "speed", cost: (l) => 60 + l * 40 },
  greed: { name: "Greed", icon: "\u2299", desc: "+8% XP gained", maxLevel: 5, per: 0.08, stat: "xp", cost: (l) => 80 + l * 50 },
  fortune: { name: "Fortune", icon: "\u29d7", desc: "+1 reroll per level-up", maxLevel: 2, per: 1, stat: "rerolls", cost: (l) => 120 + l * 120 },
  veteran: { name: "Veteran", icon: "\u2605", desc: "Start at level 1+N", maxLevel: 3, per: 1, stat: "startLevel", cost: (l) => 800 + l * 600 },
  guardian: { name: "Guardian", icon: "\u271a", desc: "Revive once per run at 50% HP", maxLevel: 1, per: 1, stat: "revives", cost: () => 2000 },
};

// Per-run environments. One is picked (and the arena rebuilt) each run.
export const BIOMES = [
  {
    id: "swamp", name: "The Mire", accent: "#7bd88f",
    sky: 0x87ceeb, fogNear: 60, fogFar: 170, sun: 0xfff2cc,
    ground: 0x2d5a3d, grid: 0x1e3b27, border: 0x4a2a1a,
    rock: 0x6d6d6d, trunk: 0x5d3b1e, leaf: 0x2f7d3a, rocks: 70, trees: 40,
  },
  {
    id: "ash", name: "Ashlands", accent: "#ff8a65",
    sky: 0x5a4038, fogNear: 40, fogFar: 130, sun: 0xffb080,
    ground: 0x3a2c26, grid: 0x2a1e19, border: 0x2a1a14,
    rock: 0x4d4a48, trunk: 0x3a2a22, leaf: 0x7a4a2a, rocks: 95, trees: 18,
  },
  {
    id: "frost", name: "Frostfen", accent: "#81d4fa",
    sky: 0xcfe6f5, fogNear: 50, fogFar: 150, sun: 0xe8f2ff,
    ground: 0xc9d6de, grid: 0xa9bcc9, border: 0x8fa3ad,
    rock: 0x9fb2bc, trunk: 0x5d4037, leaf: 0x6f9c86, rocks: 55, trees: 48,
  },
  {
    id: "ember", name: "Emberwaste", accent: "#ff7043",
    sky: 0x6b3a2a, fogNear: 35, fogFar: 115, sun: 0xff9a5a,
    ground: 0x4a2b23, grid: 0x331d17, border: 0x2a1510,
    rock: 0x3a3535, trunk: 0x4a2a1a, leaf: 0x9a3a1a, rocks: 85, trees: 22,
  },
];

// Biome hazards: telegraphed ground effects that threaten the player (and can
// be used against enemies). One entry per biome id.
export const HAZARDS = {
  // choking bog: slows + rots anything standing in it
  swamp: { kind: "bog", color: "#7bd88f", interval: 6.5, telegraph: 1.0, duration: 5.0, radius: 3.2, dps: 6, slow: 0.4 },
  // burning ground: heavy damage to player and enemies
  ash: { kind: "fire", color: "#ff7043", interval: 5.5, telegraph: 0.9, duration: 4.5, radius: 3.0, dps: 12 },
  // ice sheet: strong slow, light chill damage
  frost: { kind: "ice", color: "#81d4fa", interval: 6.0, telegraph: 0.8, duration: 5.0, radius: 3.2, dps: 3, slow: 0.5 },
  // ember strike: telegraphed meteor that bursts for heavy damage
  ember: { kind: "ember", color: "#ffab40", interval: 4.5, telegraph: 0.9, duration: 0.3, radius: 2.4, damage: 26 },
};

// In-run merchant: spawn cadence and its stock. Gold is run-scoped (lost on
// death); Essence is the persistent meta currency — the two never mix.
export const SHOP = {
  every: 75,
  stay: 26,
  reach: 2.4,
  services: [
    { id: "potion", name: "Potion", icon: "\u2764", desc: "Heal 30 HP", cost: 12 },
    { id: "reroll", name: "Reroll", icon: "\u29d7", desc: "+1 reroll", cost: 15 },
    { id: "anvil", name: "Anvil", icon: "\u271a", desc: "+15 max HP, heals 15", cost: 35 },
    { id: "bomb", name: "Bomb", icon: "\u2622", desc: "Detonate the arena", cost: 20 },
  ],
  weaponCost: { common: 25, uncommon: 35, rare: 50 },
};

// Dash / dodge: a burst of movement on a cooldown, with brief invulnerability.
export const DASH = {
  cooldown: 2.6,
  duration: 0.16,
  speed: 34,
  invuln: 0.3,
};

export const TIERS = {
  common: { color: "#9aa7b2", weight: 100 },
  uncommon: { color: "#5dd67a", weight: 42 },
  rare: { color: "#4fa3ff", weight: 14 },
  fusion: { color: "#ffd54f", weight: 220 },
};

// Sub-weapons. `kind` drives the update routine; `tags` decide which global
// stats apply (count -> multishot, area -> reach, pierce -> piercing).
export const WEAPONS = {
  main: {
    name: "Blaster",
    icon: "\u2316",
    color: "#ffe082",
    kind: "main",
    style: "shot",
    main: true,
    tags: ["count", "pierce"],
    tier: "common",
    maxLevel: 8,
    desc: "Balanced straight shots.",
    base: {
      damage: GAME.baseDamage,
      fireRate: GAME.startFireRate,
      speed: GAME.projectileSpeed,
      count: 1,
    },
    per: { damage: 3, fireRate: 0.25, speed: 1.2, countEvery: 4 },
  },
  cleaver: {
    name: "Cleaver",
    icon: "\u2694",
    color: "#ff8a65",
    kind: "main",
    style: "arc",
    main: true,
    starter: true,
    tags: ["area"],
    tier: "common",
    maxLevel: 8,
    desc: "Wide melee arc, heavy damage up close.",
    base: { damage: 26, fireRate: 1.6, range: 3.4, arcDeg: 150 },
    per: { damage: 8, fireRate: 0.12, range: 0.18, arcDeg: 4 },
  },
  hex: {
    name: "Hexbolt",
    icon: "\u2734",
    color: "#b39ddb",
    kind: "main",
    style: "seek",
    main: true,
    starter: true,
    tags: ["count"],
    tier: "common",
    maxLevel: 8,
    desc: "Fast seeking bolts, light damage.",
    base: { damage: 7, fireRate: 3.6, speed: 52, count: 1 },
    per: { damage: 2, fireRate: 0.25, speed: 2, countEvery: 4 },
  },
  shard: {
    name: "Orbital Shard",
    icon: "\u25c8",
    color: "#5ee1ff",
    kind: "orbit",
    tags: ["count", "area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "Discs orbit you, shredding enemies on contact.",
    base: { count: 1, radius: 2.6, speed: 2.0, damage: 7, tick: 0.45 },
    per: { countEvery: 2, radius: 0.22, speed: 0.15, damage: 4, tick: -0.03 },
  },
  thunder: {
    name: "Thunder Strike",
    icon: "\u26a1",
    color: "#ffe082",
    kind: "timer",
    trigger: "thunder",
    tags: ["count", "area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "Lightning hammers random enemies.",
    base: { cooldown: 2.4, damage: 24, area: 2.4, strikes: 1 },
    per: { cooldown: -0.18, damage: 10, area: 0.14, strikesEvery: 2 },
  },
  chain: {
    name: "Chain Lightning",
    icon: "\u2301",
    color: "#9fd6ff",
    kind: "timer",
    trigger: "chain",
    tags: ["count"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "A bolt arcs from foe to foe.",
    base: { cooldown: 2.2, damage: 16, jumps: 2, jumpRange: 6.5 },
    per: { cooldown: -0.16, damage: 8, jumpsEvery: 2, jumpRange: 0.4 },
  },
  spores: {
    name: "Bog Spores",
    icon: "\u2601",
    color: "#7bd88f",
    kind: "aura",
    tags: ["area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "A toxic cloud rots and slows nearby foes.",
    base: { radius: 3.0, dps: 7, slow: 0.3 },
    per: { radius: 0.28, dps: 3.2, slow: 0.03 },
  },
  wisp: {
    name: "Firefly Wisps",
    icon: "\u2726",
    color: "#ffd54f",
    kind: "homing",
    trigger: "wisp",
    tags: ["count", "area"],
    tier: "common",
    maxLevel: 6,
    desc: "Wisps seek foes and burst on impact.",
    base: { cooldown: 1.5, damage: 12, count: 1, speed: 15, blast: 1.3 },
    per: { cooldown: -0.12, damage: 5, countEvery: 2, speed: 0.5, blast: 0.1 },
  },
  leech: {
    name: "Leech Swarm",
    icon: "\u2765",
    color: "#ef7a7a",
    kind: "homing",
    trigger: "leech",
    tags: ["count"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "Leeches latch on, draining life to you.",
    base: { cooldown: 2.6, damage: 9, count: 1, speed: 12, drain: 0.4 },
    per: { cooldown: -0.2, damage: 4, countEvery: 2, speed: 0.4, drain: 0.06 },
  },
  root: {
    name: "Snare Roots",
    icon: "\u2618",
    color: "#a1887f",
    kind: "timer",
    trigger: "root",
    tags: ["count", "area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "Roots erupt, holding enemies in place.",
    base: { cooldown: 2.6, damage: 14, area: 2.0, hold: 1.2, count: 1 },
    per: { cooldown: -0.18, damage: 6, area: 0.12, hold: 0.15, countEvery: 2 },
  },
  gas: {
    name: "Swamp Gas",
    icon: "\u2623",
    color: "#9ccc65",
    kind: "reactive",
    trigger: "gas",
    tags: ["area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "Slain enemies burst into corrosive gas.",
    base: { damage: 12, area: 1.8, duration: 1.1 },
    per: { damage: 4, area: 0.14, duration: 0.12 },
  },
  totem: {
    name: "Blight Totem",
    icon: "\u265c",
    color: "#ffb74d",
    kind: "deploy",
    trigger: "totem",
    tags: ["count", "area"],
    tier: "rare",
    maxLevel: 6,
    desc: "Deploys a totem that fires at nearby foes.",
    base: { cooldown: 5.0, life: 6, damage: 10, count: 1, radius: 9, rate: 0.9 },
    per: { cooldown: -0.4, life: 0.5, damage: 4, radius: 0.4, rate: -0.08, countEvery: 3 },
  },
  thorn: {
    name: "Thorn Nova",
    icon: "\u2739",
    color: "#ef9a9a",
    kind: "reactive",
    trigger: "thorn",
    tags: ["area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "Taking a hit bursts a knocking shockwave.",
    base: { cooldown: 1.2, damage: 18, area: 3.2 },
    per: { cooldown: -0.1, damage: 8, area: 0.3 },
  },
  nova: {
    name: "Nova Pulse",
    icon: "\u2742",
    color: "#ffb300",
    kind: "timer",
    trigger: "nova",
    tags: ["area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "Periodic shockwave that blasts everything nearby.",
    base: { cooldown: 3.0, damage: 20, area: 3.6 },
    per: { cooldown: -0.2, damage: 8, area: 0.22 },
  },
  frost: {
    name: "Frost Aura",
    icon: "\u2744",
    color: "#81d4fa",
    kind: "aura",
    tags: ["area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "A chilling field that heavily slows nearby foes.",
    base: { radius: 3.2, dps: 4, slow: 0.5 },
    per: { radius: 0.25, dps: 1.6, slow: 0.04 },
  },
  ripper: {
    name: "Ripper",
    icon: "\u25c9",
    color: "#b0bec5",
    kind: "orbit",
    tags: ["count", "area"],
    tier: "common",
    maxLevel: 6,
    desc: "Fewer, larger discs that hit far harder.",
    base: { count: 1, radius: 3.2, speed: 3.2, damage: 14, tick: 0.3 },
    per: { countEvery: 2, radius: 0.2, speed: 0.2, damage: 6, tick: -0.02 },
  },
  beam: {
    name: "Beam",
    icon: "\u21f6",
    color: "#f48fb1",
    kind: "timer",
    trigger: "beam",
    tags: ["area"],
    tier: "rare",
    maxLevel: 6,
    desc: "A piercing lance that skewers a whole line.",
    base: { cooldown: 2.6, damage: 30, length: 22, width: 1.2 },
    per: { cooldown: -0.18, damage: 12, length: 0.4, width: 0.1 },
  },
  spirit: {
    name: "Spirit Guard",
    icon: "\u2735",
    color: "#7fe3ff",
    kind: "spirit",
    tags: ["count", "area"],
    fused: true,
    tier: "rare",
    maxLevel: 6,
    desc: "Orbiting guards that fire seeking spirits.",
    base: { count: 2, radius: 2.8, speed: 2.2, damage: 9, tick: 0.4, cooldown: 1.7, wispDamage: 11 },
    per: { countEvery: 2, radius: 0.2, speed: 0.15, damage: 4, tick: -0.02, cooldown: -0.1, wispDamage: 5 },
  },
  storm: {
    name: "Storm Call",
    icon: "\u26c8",
    color: "#cfe8ff",
    kind: "timer",
    trigger: "storm",
    tags: ["count", "area"],
    fused: true,
    tier: "rare",
    maxLevel: 6,
    desc: "Bolts strike and arc between foes.",
    base: { cooldown: 2.0, damage: 22, area: 2.4, strikes: 2, jumps: 2, jumpRange: 7 },
    per: { cooldown: -0.16, damage: 9, area: 0.14, strikesEvery: 2, jumpsEvery: 2, jumpRange: 0.4 },
  },
  bog: {
    name: "Black Bog",
    icon: "\u224b",
    color: "#5fa86b",
    kind: "aura",
    tags: ["area"],
    fused: true,
    tier: "rare",
    maxLevel: 6,
    desc: "A reeking mire: rots, slows, and erupts on death.",
    base: { radius: 3.4, dps: 10, slow: 0.3, damage: 16, area: 2.0, duration: 1.3 },
    per: { radius: 0.28, dps: 4, slow: 0.03, damage: 6, area: 0.14, duration: 0.12 },
  },
  bramble: {
    name: "Bramble Ward",
    icon: "\u273f",
    color: "#c0a16b",
    kind: "timer",
    trigger: "bramble",
    tags: ["count", "area"],
    fused: true,
    tier: "rare",
    maxLevel: 6,
    desc: "Roots erupt and pulse knockback novas.",
    base: { cooldown: 2.4, damage: 18, area: 2.4, hold: 1.4, count: 1, nova: 20, novaArea: 3.4 },
    per: { cooldown: -0.16, damage: 7, area: 0.12, hold: 0.15, countEvery: 2, nova: 8, novaArea: 0.3 },
  },
  reaper: {
    name: "Reaper",
    icon: "\u2620",
    color: "#ef5350",
    kind: "main",
    style: "arc",
    main: true,
    starter: true,
    locked: true,
    unlockCost: 300,
    tags: ["area"],
    tier: "common",
    maxLevel: 8,
    desc: "Slow, devastating wide cleaves.",
    base: { damage: 40, fireRate: 1.0, range: 3.8, arcDeg: 200 },
    per: { damage: 12, fireRate: 0.08, range: 0.2, arcDeg: 5 },
  },
  swarm: {
    name: "Swarm",
    icon: "\u2042",
    color: "#a5d6a7",
    kind: "main",
    style: "seek",
    main: true,
    starter: true,
    locked: true,
    unlockCost: 300,
    tags: ["count"],
    tier: "common",
    maxLevel: 8,
    desc: "A rapid hail of weak seeking bolts.",
    base: { damage: 5, fireRate: 5.0, speed: 42, count: 2 },
    per: { damage: 1.5, fireRate: 0.3, speed: 1.5, countEvery: 3 },
  },
  hive: {
    name: "Hive Totem",
    icon: "\u2756",
    color: "#ff9e6d",
    kind: "hive",
    trigger: "hive",
    tags: ["count", "area"],
    fused: true,
    tier: "rare",
    maxLevel: 6,
    desc: "A totem that spawns draining leeches.",
    base: { cooldown: 5.0, life: 7, count: 1, radius: 10, rate: 0.8, damage: 8, drain: 0.4 },
    per: { cooldown: -0.4, life: 0.6, countEvery: 3, radius: 0.4, rate: -0.06, damage: 4, drain: 0.06 },
  },
  cyclone: {
    name: "Cyclone",
    icon: "\u2743",
    color: "#80deea",
    kind: "orbit",
    tags: ["count", "area"],
    fused: true,
    tier: "rare",
    maxLevel: 6,
    desc: "A storm of heavy orbiting blades.",
    base: { count: 2, radius: 3.4, speed: 3.0, damage: 12, tick: 0.3 },
    per: { countEvery: 2, radius: 0.2, speed: 0.2, damage: 5, tick: -0.02 },
  },
  glacier: {
    name: "Glacier",
    icon: "\u2745",
    color: "#b3e5fc",
    kind: "timer",
    trigger: "nova",
    tags: ["area"],
    fused: true,
    tier: "rare",
    maxLevel: 6,
    desc: "A freezing shockwave that locks foes in ice.",
    base: { cooldown: 3.2, damage: 24, area: 4.0, freeze: 1.2 },
    per: { cooldown: -0.2, damage: 9, area: 0.2, freeze: 0.15 },
  },
  miasma: {
    name: "Miasma",
    icon: "\u2741",
    color: "#8bc34a",
    kind: "aura",
    tags: ["area"],
    fused: true,
    tier: "rare",
    maxLevel: 6,
    desc: "A vast poisonous fog that rots and clings.",
    base: { radius: 3.8, dps: 10, slow: 0.4 },
    per: { radius: 0.3, dps: 4, slow: 0.04 },
  },
  railgun: {
    name: "Railgun",
    icon: "\u269b",
    color: "#d1c4e9",
    kind: "timer",
    trigger: "beam",
    tags: ["area"],
    fused: true,
    tier: "rare",
    maxLevel: 6,
    desc: "A devastating piercing lance.",
    base: { cooldown: 2.2, damage: 44, length: 26, width: 1.8 },
    per: { cooldown: -0.16, damage: 18, length: 0.4, width: 0.12 },
  },
  quake: {
    name: "Quake",
    icon: "\u26f0",
    color: "#bcaaa4",
    kind: "timer",
    trigger: "quake",
    tags: ["count", "area"],
    fused: true,
    tier: "rare",
    maxLevel: 6,
    desc: "Roots erupt and the ground buckles.",
    base: { cooldown: 3.0, damage: 20, area: 2.6, hold: 1.4, count: 1, nova: 24, novaArea: 4.0 },
    per: { cooldown: -0.2, damage: 8, area: 0.14, hold: 0.15, countEvery: 2, nova: 9, novaArea: 0.2 },
  },
};

// Fusion recipes: both ingredients must be owned and at max level. Fusing
// consumes both (freeing slots) and grants the fused weapon.
// A weapon may appear in several recipes; whichever recipe you complete first
// consumes the ingredients, so a given weapon can only be fused into ONE result
// per run (re-acquire it afterwards to pursue a different recipe).
export const FUSIONS = [
  { ingredients: ["shard", "wisp"], result: "spirit" },
  { ingredients: ["thunder", "chain"], result: "storm" },
  { ingredients: ["spores", "gas"], result: "bog" },
  { ingredients: ["root", "thorn"], result: "bramble" },
  { ingredients: ["leech", "totem"], result: "hive" },
  { ingredients: ["shard", "ripper"], result: "cyclone" },
  { ingredients: ["nova", "frost"], result: "glacier" },
  { ingredients: ["spores", "frost"], result: "miasma" },
  { ingredients: ["beam", "thunder"], result: "railgun" },
  { ingredients: ["root", "nova"], result: "quake" },
];

// Passives. `mod(mods, level)` writes the total contribution for that level,
// so modifiers are recomputed from scratch (never double-applied).
export const PASSIVES = {
  might: {
    name: "Might", icon: "\u2020", color: "#ff8a65", tier: "common", maxLevel: 8,
    desc: "All damage +12%",
    mod: (m, lv) => { m.damage *= Math.pow(1.12, lv); },
  },
  haste: {
    name: "Haste", icon: "\u29d7", color: "#4fc3f7", tier: "common", maxLevel: 8,
    desc: "All weapons +10% rate",
    mod: (m, lv) => { m.haste *= Math.pow(1.1, lv); },
  },
  vitality: {
    name: "Vitality", icon: "\u2764", color: "#ef5350", tier: "common", maxLevel: 8,
    desc: "+25 max HP, heals 25",
    mod: (m, lv) => { m.maxHpAdd += 25 * lv; },
  },
  swiftness: {
    name: "Swiftness", icon: "\u27a4", color: "#9ccc65", tier: "common", maxLevel: 6,
    desc: "+7% move speed",
    mod: (m, lv) => { m.speed *= Math.pow(1.07, lv); },
  },
  magnet: {
    name: "Magnet", icon: "\u2299", color: "#69f0ae", tier: "common", maxLevel: 4,
    desc: "+30% XP pickup range",
    mod: (m, lv) => { m.magnet *= Math.pow(1.3, lv); },
  },
  reach: {
    name: "Reach", icon: "\u25ce", color: "#ba68c8", tier: "uncommon", maxLevel: 6,
    desc: "+15% area / effect size",
    mod: (m, lv) => { m.area *= Math.pow(1.15, lv); },
  },
  crit: {
    name: "Deadeye", icon: "\u2727", color: "#ffd54f", tier: "uncommon", maxLevel: 6,
    desc: "+6% crit chance",
    mod: (m, lv) => { m.critChance += 0.06 * lv; },
  },
  multishot: {
    name: "Multishot", icon: "\u22d4", color: "#ffb74d", tier: "rare", maxLevel: 3,
    desc: "+1 shot per weapon",
    mod: (m, lv) => { m.count += lv; },
  },
  pierce: {
    name: "Piercing", icon: "\u27b7", color: "#e0e0e0", tier: "rare", maxLevel: 3,
    desc: "Shots pierce +1 foe",
    mod: (m, lv) => { m.pierce += lv; },
  },
  vampirism: {
    name: "Vampirism", icon: "\u2765", color: "#e57373", tier: "rare", maxLevel: 5,
    desc: "+2% lifesteal on damage",
    mod: (m, lv) => { m.lifesteal += 0.02 * lv; },
  },
};
