export const WORLD_SIZE = 160;

export const PLAYER = {
  radius: 0.5,
  speed: 9,
  maxHp: 100,
};

export const ENEMY_TYPES = {
  grunt: {
    radius: 0.9,
    height: 2.0,
    speed: 3.2,
    hp: 25,
    damage: 8,
    xp: 3,
    color: 0xc0392b,
    model: "/models/goblin_mini1.bbmodel",
  },
  runner: {
    radius: 0.75,
    height: 1.6,
    speed: 5.6,
    hp: 12,
    damage: 6,
    xp: 2,
    color: 0xe67e22,
    model: "/models/goblin_mini2.bbmodel",
  },
  brute: {
    radius: 1.3,
    height: 2.8,
    speed: 1.8,
    hp: 120,
    damage: 20,
    xp: 12,
    color: 0x8e44ad,
    model: "/models/goblin_mini3.bbmodel",
  },
  knight: {
    radius: 1.2,
    height: 2.6,
    speed: 2.2,
    hp: 160,
    damage: 25,
    xp: 18,
    color: 0x4a4a6a,
    model: "/models/goblin_knight.bbmodel",
  },
  leader: {
    radius: 1.0,
    height: 2.2,
    speed: 3.8,
    hp: 60,
    damage: 12,
    xp: 10,
    color: 0xd4a017,
    model: "/models/goblin_leader.bbmodel",
  },
  mage: {
    radius: 1.0,
    height: 2.4,
    speed: 3.0,
    hp: 55,
    damage: 10,
    xp: 15,
    color: 0x26c6da,
    model: "/models/goblin_mage.bbmodel",
    ranged: true,
    range: 16,
    fireInterval: 2.2,
    projectileSpeed: 12,
  },
};

export const GAME = {
  startHp: 100,
  startFireRate: 3,
  baseDamage: 12,
  projectileSpeed: 34,
  maxEnemies: 120,
  enemyScalePerMinute: 1.05,
  maxWeapons: 5,
  rerollsPerLevel: 1,
  xpToLevel: (level) => 5 + (level - 1) * 5 + Math.floor((level - 1) ** 1.4),
};

export const TIERS = {
  common: { color: "#9aa7b2", weight: 100 },
  uncommon: { color: "#5dd67a", weight: 42 },
  rare: { color: "#4fa3ff", weight: 14 },
};

// Sub-weapons. `kind` drives the update routine; `tags` decide which global
// stats apply (count -> multishot, area -> reach, pierce -> piercing).
export const WEAPONS = {
  shard: {
    name: "Orbital Shard",
    icon: "\u25c8",
    color: "#5ee1ff",
    kind: "orbit",
    tags: ["count", "area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "Discs orbit you, shredding enemies on contact.",
    base: { count: 1, radius: 2.6, speed: 2.0, damage: 7, tick: 0.45 },
    per: { countEvery: 2, radius: 0.22, speed: 0.15, damage: 4, tick: -0.03 },
  },
  thunder: {
    name: "Thunder Strike",
    icon: "\u26a1",
    color: "#ffe082",
    kind: "timer",
    trigger: "thunder",
    tags: ["count", "area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "Lightning hammers random enemies.",
    base: { cooldown: 2.4, damage: 24, area: 2.4, strikes: 1 },
    per: { cooldown: -0.18, damage: 10, area: 0.14, strikesEvery: 2 },
  },
  chain: {
    name: "Chain Lightning",
    icon: "\u2301",
    color: "#9fd6ff",
    kind: "timer",
    trigger: "chain",
    tags: ["count"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "A bolt arcs from foe to foe.",
    base: { cooldown: 2.2, damage: 16, jumps: 2, jumpRange: 6.5 },
    per: { cooldown: -0.16, damage: 8, jumpsEvery: 2, jumpRange: 0.4 },
  },
  spores: {
    name: "Bog Spores",
    icon: "\u2601",
    color: "#7bd88f",
    kind: "aura",
    tags: ["area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "A toxic cloud rots and slows nearby foes.",
    base: { radius: 3.0, dps: 7, slow: 0.3 },
    per: { radius: 0.28, dps: 3.2, slow: 0.03 },
  },
  wisp: {
    name: "Firefly Wisps",
    icon: "\u2726",
    color: "#ffd54f",
    kind: "homing",
    trigger: "wisp",
    tags: ["count", "area"],
    tier: "common",
    maxLevel: 6,
    desc: "Wisps seek foes and burst on impact.",
    base: { cooldown: 1.5, damage: 12, count: 1, speed: 15, blast: 1.3 },
    per: { cooldown: -0.12, damage: 5, countEvery: 2, speed: 0.5, blast: 0.1 },
  },
  leech: {
    name: "Leech Swarm",
    icon: "\u2765",
    color: "#ef7a7a",
    kind: "homing",
    trigger: "leech",
    tags: ["count"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "Leeches latch on, draining life to you.",
    base: { cooldown: 2.6, damage: 9, count: 1, speed: 12, drain: 0.4 },
    per: { cooldown: -0.2, damage: 4, countEvery: 2, speed: 0.4, drain: 0.06 },
  },
  root: {
    name: "Snare Roots",
    icon: "\u2618",
    color: "#a1887f",
    kind: "timer",
    trigger: "root",
    tags: ["count", "area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "Roots erupt, holding enemies in place.",
    base: { cooldown: 2.6, damage: 14, area: 2.0, hold: 1.2, count: 1 },
    per: { cooldown: -0.18, damage: 6, area: 0.12, hold: 0.15, countEvery: 2 },
  },
  gas: {
    name: "Swamp Gas",
    icon: "\u2623",
    color: "#9ccc65",
    kind: "reactive",
    trigger: "gas",
    tags: ["area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "Slain enemies burst into corrosive gas.",
    base: { damage: 12, area: 1.8, duration: 1.1 },
    per: { damage: 4, area: 0.14, duration: 0.12 },
  },
  totem: {
    name: "Blight Totem",
    icon: "\u265c",
    color: "#ffb74d",
    kind: "deploy",
    trigger: "totem",
    tags: ["count", "area"],
    tier: "rare",
    maxLevel: 6,
    desc: "Deploys a totem that fires at nearby foes.",
    base: { cooldown: 5.0, life: 6, damage: 10, count: 1, radius: 9, rate: 0.9 },
    per: { cooldown: -0.4, life: 0.5, damage: 4, radius: 0.4, rate: -0.08, countEvery: 3 },
  },
  thorn: {
    name: "Thorn Nova",
    icon: "\u2739",
    color: "#ef9a9a",
    kind: "reactive",
    trigger: "thorn",
    tags: ["area"],
    tier: "uncommon",
    maxLevel: 6,
    desc: "Taking a hit bursts a knocking shockwave.",
    base: { cooldown: 1.2, damage: 18, area: 3.2 },
    per: { cooldown: -0.1, damage: 8, area: 0.3 },
  },
};

// Passives. `mod(mods, level)` writes the total contribution for that level,
// so modifiers are recomputed from scratch (never double-applied).
export const PASSIVES = {
  might: {
    name: "Might", icon: "\u2020", color: "#ff8a65", tier: "common", maxLevel: 8,
    desc: "All damage +12%",
    mod: (m, lv) => { m.damage *= Math.pow(1.12, lv); },
  },
  haste: {
    name: "Haste", icon: "\u29d7", color: "#4fc3f7", tier: "common", maxLevel: 8,
    desc: "All weapons +10% rate",
    mod: (m, lv) => { m.haste *= Math.pow(1.1, lv); },
  },
  vitality: {
    name: "Vitality", icon: "\u2764", color: "#ef5350", tier: "common", maxLevel: 8,
    desc: "+25 max HP, heals 25",
    mod: (m, lv) => { m.maxHpAdd += 25 * lv; },
  },
  swiftness: {
    name: "Swiftness", icon: "\u27a4", color: "#9ccc65", tier: "common", maxLevel: 6,
    desc: "+7% move speed",
    mod: (m, lv) => { m.speed *= Math.pow(1.07, lv); },
  },
  magnet: {
    name: "Magnet", icon: "\u2299", color: "#69f0ae", tier: "common", maxLevel: 4,
    desc: "+30% XP pickup range",
    mod: (m, lv) => { m.magnet *= Math.pow(1.3, lv); },
  },
  reach: {
    name: "Reach", icon: "\u25ce", color: "#ba68c8", tier: "uncommon", maxLevel: 6,
    desc: "+15% area / effect size",
    mod: (m, lv) => { m.area *= Math.pow(1.15, lv); },
  },
  crit: {
    name: "Deadeye", icon: "\u2727", color: "#ffd54f", tier: "uncommon", maxLevel: 6,
    desc: "+6% crit chance",
    mod: (m, lv) => { m.critChance += 0.06 * lv; },
  },
  multishot: {
    name: "Multishot", icon: "\u22d4", color: "#ffb74d", tier: "rare", maxLevel: 3,
    desc: "+1 shot per weapon",
    mod: (m, lv) => { m.count += lv; },
  },
  pierce: {
    name: "Piercing", icon: "\u27b7", color: "#e0e0e0", tier: "rare", maxLevel: 3,
    desc: "Shots pierce +1 foe",
    mod: (m, lv) => { m.pierce += lv; },
  },
  vampirism: {
    name: "Vampirism", icon: "\u2765", color: "#e57373", tier: "rare", maxLevel: 5,
    desc: "+2% lifesteal on damage",
    mod: (m, lv) => { m.lifesteal += 0.02 * lv; },
  },
};
